const swaggerAutogen = require('swagger-autogen')();

const outputFile = './src/swagger/swagger_documentation.json';
const endpointsFiles = [
  './src/routes/BaseRoute.ts',
  './src/routes/UserRoutes.ts',
  './src/routes/PetRoutes.ts',
];

const doc = {
  info: {
    version: '1.0.0',
    title: 'ADOPT A PET API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'User',
      description: 'Endpoints',
    },
    {
      name: 'Pet',
      description: 'Endpoints',
    },
  ],
  securityDefinitions: {
    api_key: {
      type: 'apiKey',
      name: 'api_key',
      in: 'header',
    },
    petadoption_auth: {
      type: 'oauth2',
      authorizationUrl: 'https://petstore.swagger.io/oauth/authorize',
      flow: 'implicit',
      scopes: {
        read_pets: 'read your pets',
        write_pets: 'modify pets in your account',
      },
    },
  },
  definitions: {
    User: {
      name: 'Jhon Doe',
      email: 'john@doe.com',
      avatar: 'https://randomuser.me/api/portraits/',
      phone: '+5511999999999',
      role: 'user',
    },
    Pet: {
      name: 'Jhon Doe Jr',
      age: 2,
      weight: 8,
      color: 'white',
      type: 'dog',
      breed: 'labrador',
      description: 'A very cute dog',
      images: [
        'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      ],
      available: true,
      user: {
        name: 'Jhon Doe',
        email: 'jhon@doe.com',
        avatar: 'https://randomuser.me/api/portraits/',
        phone: '+5511999999999',
      },
      adopter: {
        name: 'Samantha Jim',
        email: 'sammy@jim.com',
        avatar: 'https://randomuser.me/api/portraits/',
        phone: '+5511555555555',
      },
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc);
